const PRODUCT_ID_KEY = '{{ PRODUCT_ID_KEY }}';
const PRODUCT_TITLE_KEY = '{{ PRODUCT_TITLE_KEY }}';
const PRODUCT_PRODUCER_NAME_KEY = '{{ PRODUCT_PRODUCER_NAME_KEY }}';
const PRODUCT_PRODUCER_URL_KEY = '{{ PRODUCT_PRODUCER_URL_KEY }}';
const PRODUCT_PRICE_KEY = '{{ PRODUCT_PRICE_KEY }}';
const PRODUCT_OMNIBUS_KEY = '{{ PRODUCT_OMNIBUS_KEY }}';
const PRODUCT_IMAGE_URL_KEY = '{{ PRODUCT_IMAGE_URL_KEY }}';
const PRODUCT_LINK_KEY = '{{ PRODUCT_LINK_KEY }}';
const PRODUCT_DESCRIPTION_KEY = '{{ PRODUCT_DESCRIPTION_KEY }}';
const PRODUCT_POINTS_KEY = '{{ PRODUCT_POINTS_KEY }}';
const PRODUCT_PRICE_MAX_KEY = '{{ PRODUCT_PRICE_MAX_KEY }}';

const CONTENT = 'CONTENT';

export {
  PRODUCT_ID_KEY,
  PRODUCT_TITLE_KEY,
  PRODUCT_PRODUCER_NAME_KEY,
  PRODUCT_PRODUCER_URL_KEY,
  PRODUCT_PRICE_KEY,
  PRODUCT_OMNIBUS_KEY,
  PRODUCT_IMAGE_URL_KEY,
  PRODUCT_LINK_KEY,
  PRODUCT_DESCRIPTION_KEY,
  CONTENT,
  PRODUCT_POINTS_KEY,
  PRODUCT_PRICE_MAX_KEY,
};
