const PRODUCT_ID_KEY = '{{ PRODUCT_ID_KEY }}';
const PRODUCT_TITLE_KEY = '{{ PRODUCT_TITLE_KEY }}';
const PRODUCT_PRODUCER_NAME_KEY = '{{ PRODUCT_PRODUCER_NAME_KEY }}';
const PRODUCT_PRODUCER_URL_KEY = '{{ PRODUCT_PRODUCER_URL_KEY }}';
const PRODUCT_PRICE_MAIN_KEY = '{{ PRODUCT_PRICE_MAIN_KEY }}';
const PRODUCT_PRICE_PERCENT_KEY = '{{ PRODUCT_PRICE_PERCENT_KEY }}';
const PRODUCT_PRICE_OMNIBUS_KEY = '{{ PRODUCT_PRICE_OMNIBUS_KEY }}';
const PRODUCT_PRICE_OMNIBUS_PERCENT_KEY =
  '{{ PRODUCT_PRICE_OMNIBUS_PERCENT_KEY }}';
const PRODUCT_IMAGE_URL_KEY = '{{ PRODUCT_IMAGE_URL_KEY }}';
const PRODUCT_LINK_KEY = '{{ PRODUCT_LINK_KEY }}';
const PRODUCT_DESCRIPTION_KEY = '{{ PRODUCT_DESCRIPTION_KEY }}';
const PRODUCT_DESCRIPTION_TRAIT_KEY = '{{ PRODUCT_DESCRIPTION_TRAIT_KEY }}';
const PRODUCT_POINTS_KEY = '{{ PRODUCT_POINTS_KEY }}';
const PRODUCT_PRICE_REGULAR_KEY = '{{ PRODUCT_PRICE_REGULAR_KEY }}';
const PRODUCT_SIZE = '{{ PRODUCT_SIZE }}';

const CONTENT = 'CONTENT';

export {
  PRODUCT_ID_KEY,
  PRODUCT_TITLE_KEY,
  PRODUCT_PRODUCER_NAME_KEY,
  PRODUCT_PRODUCER_URL_KEY,
  PRODUCT_PRICE_MAIN_KEY,
  PRODUCT_PRICE_OMNIBUS_KEY,
  PRODUCT_IMAGE_URL_KEY,
  PRODUCT_LINK_KEY,
  PRODUCT_DESCRIPTION_KEY,
  CONTENT,
  PRODUCT_POINTS_KEY,
  PRODUCT_PRICE_REGULAR_KEY,
  PRODUCT_PRICE_PERCENT_KEY,
  PRODUCT_PRICE_OMNIBUS_PERCENT_KEY,
  PRODUCT_DESCRIPTION_TRAIT_KEY,
  PRODUCT_SIZE,
};
