import {
  BASKET_PAGE,
  BASKET_PAGE_HOTSPOT,
  MAIN_PAGE,
  MAIN_PAGE_HOTSPOT_FOUR,
  MAIN_PAGE_HOTSPOT_ONE,
  MAIN_PAGE_HOTSPOT_THREE,
  MAIN_PAGE_HOTSPOT_TWO,
  PRODUCTS_LIST,
  PRODUCT_DETAILS_ASSOCIATED_ONE,
  PRODUCT_DETAILS_ASSOCIATED_THREE,
  PRODUCT_DETAILS_ASSOCIATED_TWO,
  PRODUCT_DETAILS_PAGE,
  PRODUCT_LISTING,
  PRODUCT_LISTING_HOTSPOT,
} from 'consts/pages';

type TPages =
  | typeof PRODUCTS_LIST
  | typeof PRODUCT_DETAILS_PAGE
  | typeof MAIN_PAGE
  | typeof BASKET_PAGE;

type TProductDetailsZones =
  | typeof PRODUCT_DETAILS_ASSOCIATED_ONE
  | typeof PRODUCT_DETAILS_ASSOCIATED_TWO
  | typeof PRODUCT_DETAILS_ASSOCIATED_THREE;

type TMainPageZones =
  | typeof MAIN_PAGE_HOTSPOT_ONE
  | typeof MAIN_PAGE_HOTSPOT_TWO
  | typeof MAIN_PAGE_HOTSPOT_THREE
  | typeof MAIN_PAGE_HOTSPOT_FOUR;

type TListingPageZones =
  | typeof PRODUCT_LISTING
  | typeof PRODUCT_LISTING_HOTSPOT;

type TBasketPageZones = typeof BASKET_PAGE_HOTSPOT;

export type {
  TPages,
  TProductDetailsZones,
  TMainPageZones,
  TListingPageZones,
  TBasketPageZones,
};
