const PRODUCTS_LIST = 'PRODUCTS_LIST';
const BASKET_PAGE = 'BASKET_PAGE';
const PRODUCT_DETAILS_PAGE = 'PRODUCT_DETAILS_PAGE';
const MAIN_PAGE = 'MAIN_PAGE';

const PRODUCT_DETAILS_PAGE_SELECTOR = '#projector_form';
const BASKET_PAGE_SELECTOR = '#Basket';
const MAIN_PAGE_SELECTOR = '.main_page';
const MAIN_PAGE_CONTAINER_CLASS = 'main_page';

// Basket zones
const BASKET_PAGE_HOTSPOT = 'BASKET_PAGE_HOTSPOT';

// Listing zones
const PRODUCT_LISTING = 'PRODUCT_LISTING';
const PRODUCT_LISTING_HOTSPOT = 'PRODUCT_LISTING_HOTSPOT';

// Product detail page zones
const PRODUCT_DETAILS_ASSOCIATED_ONE = 'PRODUCT_DETAILS_ASSOCIATED_ONE';
const PRODUCT_DETAILS_ASSOCIATED_TWO = 'PRODUCT_DETAILS_ASSOCIATED_TWO';
const PRODUCT_DETAILS_ASSOCIATED_THREE = 'PRODUCT_DETAILS_ASSOCIATED_THREE';
const PRODUCT_DETAILS_ASSOCIATED_FOUR = 'PRODUCT_DETAILS_ASSOCIATED_FOUR';
const PRODUCT_DETAILS_PRODUCTS_ZONE_ONE = 'PRODUCT_DETAILS_PRODUCTS_ZONE_ONE';

// Main page zones
const MAIN_PAGE_HOTSPOT_ONE = 'MAIN_PAGE_HOTSPOT_ONE';
const MAIN_PAGE_HOTSPOT_TWO = 'MAIN_PAGE_HOTSPOT_TWO';
const MAIN_PAGE_HOTSPOT_THREE = 'MAIN_PAGE_HOTSPOT_THREE';
const MAIN_PAGE_HOTSPOT_FOUR = 'MAIN_PAGE_HOTSPOT_FOUR';

export {
  BASKET_PAGE,
  BASKET_PAGE_HOTSPOT,
  BASKET_PAGE_SELECTOR,
  PRODUCTS_LIST,
  PRODUCT_LISTING,
  PRODUCT_LISTING_HOTSPOT,
  PRODUCT_DETAILS_PAGE,
  PRODUCT_DETAILS_ASSOCIATED_ONE,
  PRODUCT_DETAILS_ASSOCIATED_TWO,
  PRODUCT_DETAILS_ASSOCIATED_THREE,
  PRODUCT_DETAILS_ASSOCIATED_FOUR,
  PRODUCT_DETAILS_PRODUCTS_ZONE_ONE,
  PRODUCT_DETAILS_PAGE_SELECTOR,
  MAIN_PAGE,
  MAIN_PAGE_HOTSPOT_ONE,
  MAIN_PAGE_HOTSPOT_TWO,
  MAIN_PAGE_HOTSPOT_THREE,
  MAIN_PAGE_HOTSPOT_FOUR,
  MAIN_PAGE_SELECTOR,
  MAIN_PAGE_CONTAINER_CLASS,
};
