const PRODUCTS_LIST = 'PRODUCTS_LIST';
const PRODUCT_DETAILS_PAGE = 'PRODUCT_DETAILS_PAGE';
const MAIN_PAGE = 'MAIN_PAGE';

const PRODUCT_DETAILS_PAGE_SELECTOR = '#projector_form';
const MAIN_PAGE_SELECTOR = '#container';
const MAIN_PAGE_CONTAINER_CLASS = 'main_page';

// Listing zones

const PRODUCT_LISTING = 'PRODUCT_LISTING';
const PRODUCT_LISTING_HOTSPOT = 'PRODUCT_LISTING_HOTSPOT';

// Product detail page zones
const PRODUCT_DETAILS_ASSOCIATED_ONE = 'PRODUCT_DETAILS_ASSOCIATED_ONE';
const PRODUCT_DETAILS_ASSOCIATED_TWO = 'PRODUCT_DETAILS_ASSOCIATED_TWO';

// Main page zones
const MAIN_PAGE_HOTSPOT_ONE = 'MAIN_PAGE_HOTSPOT_ONE';
const MAIN_PAGE_HOTSPOT_TWO = 'MAIN_PAGE_HOTSPOT_TWO';
const MAIN_PAGE_HOTSPOT_THREE = 'MAIN_PAGE_HOTSPOT_THREE';
const MAIN_PAGE_HOTSPOT_FOUR = 'MAIN_PAGE_HOTSPOT_FOUR';

export {
  PRODUCTS_LIST,
  PRODUCT_DETAILS_ASSOCIATED_ONE,
  PRODUCT_DETAILS_ASSOCIATED_TWO,
  PRODUCT_DETAILS_PAGE,
  MAIN_PAGE,
  MAIN_PAGE_HOTSPOT_ONE,
  MAIN_PAGE_HOTSPOT_TWO,
  MAIN_PAGE_HOTSPOT_THREE,
  PRODUCT_DETAILS_PAGE_SELECTOR,
  MAIN_PAGE_SELECTOR,
  MAIN_PAGE_CONTAINER_CLASS,
  PRODUCT_LISTING,
  PRODUCT_LISTING_HOTSPOT,
  MAIN_PAGE_HOTSPOT_FOUR,
};
