import {
  MAIN_PAGE,
  MAIN_PAGE_HOTSPOT_FOUR,
  MAIN_PAGE_HOTSPOT_ONE,
  MAIN_PAGE_HOTSPOT_THREE,
  MAIN_PAGE_HOTSPOT_TWO,
  PRODUCTS_LIST,
  PRODUCT_DETAILS_ASSOCIATED_ONE,
  PRODUCT_DETAILS_ASSOCIATED_TWO,
  PRODUCT_DETAILS_PAGE,
  PRODUCT_LISTING,
  PRODUCT_LISTING_HOTSPOT,
} from 'consts/pages';
import {
  TProductContainers,
  TProductIdExtractorKeys,
  TProductSelectors,
} from 'types/product';

const PRODUCT_LISTING_SELECTOR = '#search';
const PRODUCT_LISTING_HOTSPOT_SELECTOR = '#search_hotspot_zone1 .products';

const ASSOCIATED_ONE_PORODUCTS_LIST_SELECTOR =
  '#products_associated_zone1 .products';
const ASSOCIATED_TWO_PORODUCTS_LIST_SELECTOR = '#products_associated_zone2';

const MAIN_PAGE_HOT_SPOT_ONE_LIST_SELECTOR = '#main_hotspot_zone1 .products';
const MAIN_PAGE_HOT_SPOT_TWO_LIST_SELECTOR = '#main_hotspot_zone2 .products';
const MAIN_PAGE_HOT_SPOT_THREE_LIST_SELECTOR = '#main_hotspot_zone3 .products';
const MAIN_PAGE_HOT_SPOT_THREE_LIST_FOUR = '#main_hotspot_zone4 .products';

const PRODUCT_DISABLE_KEY = 'product_disable';
const PRODUCT_CLASS = 'product';
const PRODUCT_SELECTOR = `.${PRODUCT_CLASS}`;

const PRODUCT_LISTING_ID = 'data-product_id';
const PRODUCT_LISTING_ID_SELECTOR = `[${PRODUCT_LISTING_ID}]`;
const PRODUCT_LISTING_ID_EXTRACTOR_KEY = 'product_id';

const HOT_SPOTS_PRODUCT_ID = 'data-product-id';
const HOT_SPOTS_PRODUCT_ID_SELECTOR = `[${HOT_SPOTS_PRODUCT_ID}]`;
const HOT_SPOTS_PRODUCT_EXTRACTOR_KEY = 'productId';

const PRODUCT_CONTAINERS: TProductContainers = {
  [PRODUCTS_LIST]: {
    [PRODUCT_LISTING]: PRODUCT_LISTING_SELECTOR,
    [PRODUCT_LISTING_HOTSPOT]: PRODUCT_LISTING_HOTSPOT_SELECTOR,
  },

  [PRODUCT_DETAILS_PAGE]: {
    [PRODUCT_DETAILS_ASSOCIATED_ONE]: ASSOCIATED_ONE_PORODUCTS_LIST_SELECTOR,
    [PRODUCT_DETAILS_ASSOCIATED_TWO]: ASSOCIATED_TWO_PORODUCTS_LIST_SELECTOR,
  },

  [MAIN_PAGE]: {
    [MAIN_PAGE_HOTSPOT_ONE]: MAIN_PAGE_HOT_SPOT_ONE_LIST_SELECTOR,
    [MAIN_PAGE_HOTSPOT_TWO]: MAIN_PAGE_HOT_SPOT_TWO_LIST_SELECTOR,
    [MAIN_PAGE_HOTSPOT_THREE]: MAIN_PAGE_HOT_SPOT_THREE_LIST_SELECTOR,
    [MAIN_PAGE_HOTSPOT_FOUR]: MAIN_PAGE_HOT_SPOT_THREE_LIST_FOUR,
  },
};

const PRODUCT_ID_SELECTORS: TProductSelectors = {
  [PRODUCTS_LIST]: {
    [PRODUCT_LISTING]: PRODUCT_LISTING_ID_SELECTOR,
    [PRODUCT_LISTING_HOTSPOT]: HOT_SPOTS_PRODUCT_ID_SELECTOR,
  },
  [PRODUCT_DETAILS_PAGE]: {
    [PRODUCT_DETAILS_ASSOCIATED_ONE]: HOT_SPOTS_PRODUCT_ID_SELECTOR,
    [PRODUCT_DETAILS_ASSOCIATED_TWO]: HOT_SPOTS_PRODUCT_ID_SELECTOR,
  },
  [MAIN_PAGE]: {
    [MAIN_PAGE_HOTSPOT_ONE]: HOT_SPOTS_PRODUCT_ID_SELECTOR,
    [MAIN_PAGE_HOTSPOT_TWO]: HOT_SPOTS_PRODUCT_ID_SELECTOR,
    [MAIN_PAGE_HOTSPOT_THREE]: HOT_SPOTS_PRODUCT_ID_SELECTOR,
    [MAIN_PAGE_HOTSPOT_FOUR]: HOT_SPOTS_PRODUCT_ID_SELECTOR,
  },
};

const PRODUCT_ID_EXTRACTOR_KEYS: TProductIdExtractorKeys = {
  [PRODUCTS_LIST]: {
    [PRODUCT_LISTING]: PRODUCT_LISTING_ID_EXTRACTOR_KEY,
    [PRODUCT_LISTING_HOTSPOT]: HOT_SPOTS_PRODUCT_EXTRACTOR_KEY,
  },
  [PRODUCT_DETAILS_PAGE]: {
    [PRODUCT_DETAILS_ASSOCIATED_ONE]: HOT_SPOTS_PRODUCT_EXTRACTOR_KEY,
    [PRODUCT_DETAILS_ASSOCIATED_TWO]: HOT_SPOTS_PRODUCT_EXTRACTOR_KEY,
  },
  [MAIN_PAGE]: {
    [MAIN_PAGE_HOTSPOT_ONE]: HOT_SPOTS_PRODUCT_EXTRACTOR_KEY,
    [MAIN_PAGE_HOTSPOT_TWO]: HOT_SPOTS_PRODUCT_EXTRACTOR_KEY,
    [MAIN_PAGE_HOTSPOT_THREE]: HOT_SPOTS_PRODUCT_EXTRACTOR_KEY,
    [MAIN_PAGE_HOTSPOT_FOUR]: HOT_SPOTS_PRODUCT_EXTRACTOR_KEY,
  },
};

const CONTAINER_SELECTORS_TO_DELETE = ['.product__traits', '.label_icons'];

const SLIDER_CLASS = '--slider';

export {
  PRODUCT_LISTING_SELECTOR,
  PRODUCT_CONTAINERS,
  ASSOCIATED_ONE_PORODUCTS_LIST_SELECTOR,
  ASSOCIATED_TWO_PORODUCTS_LIST_SELECTOR,
  PRODUCT_ID_SELECTORS,
  PRODUCT_CLASS,
  PRODUCT_DISABLE_KEY,
  PRODUCT_ID_EXTRACTOR_KEYS,
  PRODUCT_SELECTOR,
  CONTAINER_SELECTORS_TO_DELETE,
  SLIDER_CLASS,
};
