import {
  BASKET_PAGE_HOTSPOT,
  MAIN_PAGE_HOTSPOT_FOUR,
  MAIN_PAGE_HOTSPOT_ONE,
  MAIN_PAGE_HOTSPOT_THREE,
  MAIN_PAGE_HOTSPOT_TWO,
  PRODUCT_DETAILS_ASSOCIATED_FOUR,
  PRODUCT_DETAILS_ASSOCIATED_ONE,
  PRODUCT_DETAILS_ASSOCIATED_THREE,
  PRODUCT_DETAILS_ASSOCIATED_TWO,
  PRODUCT_LISTING,
  PRODUCT_LISTING_HOTSPOT,
} from 'consts/pages';
import { ETemplates } from 'types/templates';

const TEMPLATES_MAP = {
  [PRODUCT_LISTING]: ETemplates.PRODUCT_LISTING,
  [PRODUCT_LISTING_HOTSPOT]: ETemplates.PRODUCT_LISTING_HOTSPOT,
  [BASKET_PAGE_HOTSPOT]: ETemplates.BASKET_PAGE_HOTSPOT,

  [PRODUCT_DETAILS_ASSOCIATED_ONE]: ETemplates.PRODUCT_DETAILS_ASSOCIATED_ONE,
  [PRODUCT_DETAILS_ASSOCIATED_TWO]: ETemplates.PRODUCT_DETAILS_ASSOCIATED_TWO,
  [PRODUCT_DETAILS_ASSOCIATED_THREE]:
    ETemplates.PRODUCT_DETAILS_ASSOCIATED_THREE,
  [PRODUCT_DETAILS_ASSOCIATED_FOUR]: ETemplates.PRODUCT_DETAILS_ASSOCIATED_FOUR,

  [MAIN_PAGE_HOTSPOT_ONE]: ETemplates.MAIN_PAGE_HOTSPOT_ONE,
  [MAIN_PAGE_HOTSPOT_TWO]: ETemplates.MAIN_PAGE_HOTSPOT_TWO,
  [MAIN_PAGE_HOTSPOT_THREE]: ETemplates.MAIN_PAGE_HOTSPOT_THREE,
  [MAIN_PAGE_HOTSPOT_FOUR]: ETemplates.MAIN_PAGE_HOTSPOT_FOUR,
};

const NOT_VALID_TEMPLATE = 'NOT_VALID_TEMPLATE';

export { TEMPLATES_MAP, NOT_VALID_TEMPLATE };
