import {
  MAIN_PAGE_HOTSPOT_ONE,
  MAIN_PAGE_HOTSPOT_THREE,
  MAIN_PAGE_HOTSPOT_TWO,
  PRODUCTS_LIST,
  PRODUCT_DETAILS_ASSOCIATED_ONE,
  PRODUCT_DETAILS_ASSOCIATED_TWO,
} from 'consts/pages';
import { ETemplates } from 'types/templates';

const TEMPLATES_MAP = {
  [PRODUCTS_LIST]: ETemplates.PRODUCTS_LISTING,
  [PRODUCT_DETAILS_ASSOCIATED_ONE]: ETemplates.PRODUCT_DETAILS_ASSOCIATED_ONE,
  [PRODUCT_DETAILS_ASSOCIATED_TWO]: ETemplates.PRODUCT_DETAILS_ASSOCIATED_TWO,
  [MAIN_PAGE_HOTSPOT_ONE]: ETemplates.MAIN_PAGE_HOTSPOT_ONE,
  [MAIN_PAGE_HOTSPOT_TWO]: ETemplates.MAIN_PAGE_HOTSPOT_TWO,
  [MAIN_PAGE_HOTSPOT_THREE]: ETemplates.MAIN_PAGE_HOTSPOT_THREE,
};

const NOT_VALID_TEMPLATE = 'NOT_VALID_TEMPLATE';

export { TEMPLATES_MAP, NOT_VALID_TEMPLATE };
