import {
  PRODUCTS_LIST,
  PRODUCT_DETAILS_ASSOCIATED_ONE,
  PRODUCT_DETAILS_ASSOCIATED_TWO,
} from 'consts/pages';
import { ETemplates } from 'types/templates';

const TEMPLATES_MAP = {
  [PRODUCTS_LIST]: ETemplates.PRODUCTS_LISTING,
  [PRODUCT_DETAILS_ASSOCIATED_ONE]: ETemplates.ASSOCIATED_PRODUCTS_LISTING_ONE,
  [PRODUCT_DETAILS_ASSOCIATED_TWO]: ETemplates.ASSOCIATED_PRODUCTS_LISTING_TWO,
};

const NOT_VALID_TEMPLATE = 'NOT_VALID_TEMPLATE';

export { TEMPLATES_MAP, NOT_VALID_TEMPLATE };
